---
- name: Kubernetes node check
  hosts: k8s_nodes
  become: yes

  tasks:

    - name: Check hostname
      command: hostname
      register: hostname

    - name: Check kernel
      command: uname -r
      register: kernel

    - name: Check containerd status
      systemd:
        name: containerd
      register: containerd_status

    - name: Check kubelet status
      systemd:
        name: kubelet
      register: kubelet_status


    - name: Show hostname
      debug:
        msg: "{{ hostname.stdout }}"


    - name: Show kernel
      debug:
        msg: "{{ kernel.stdout }}"


    - name: Show containerd
      debug:
        msg: "{{ containerd_status.status.ActiveState }}"


    - name: Show kubelet
      debug:
        msg: "{{ kubelet_status.status.ActiveState }}"
